#!/usr/bin/env python3

import argparse
import os

parser = argparse.ArgumentParser(prog='woodo')
parser = argparse.ArgumentParser(description='Must be run with elevated privileges.')
args = parser.parse_args()
if os.geteuid() != 0:
   print('Please run this script again with root.')
else:
   import sw
